# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/python/black
    rev: 22.3.0
    hooks:
    -   id: black

-   repo: https://github.com/sqlalchemyorg/zimports
    rev: v0.6.0
    hooks:
    -   id: zimports
        args:
            - --keep-unused-type-checking

-   repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        additional_dependencies:
          - flake8-import-order
          - flake8-builtins
          - pygments
